### PR TITLE
DCCR-20: proposed sessions list

### PR DESCRIPTION
**Pull request by dharizza**
Here we have the porpossed sessions list, the index and the views related.

### CODE REVIEW

**Comment by dharizza** [comment]
@kporras07 @rigoucr Now you can check.

**Comment by rigoucr** [comment]
- Please change the format of display the items in the view to table format.
- Add the respective text to the header.
- Add Date created to index.
- Add sort criteria by Date created (descending).

**Comment by dharizza** [comment]
Hi, ready with your comments except for the one about the text in the header, I'll put that text in another block. 
Please check, thanks.

**Comment by dharizza** [comment]
Fixed merge conflicts.

**Comment by kporras07** [comment]
Please apply this patch to dccr_ftr_config for changing server name (just to be sure it matches with the other index server's name)
https://gist.github.com/kporras07/a41dc7b06d69c736fd2f

**Comment by kporras07** [comment]
Only if it doesn't is so much work: do you think is easy to change the index machine name? If it's much work; please don't do it.

**Comment by kporras07** [comment]
Just fyi; we are adding contrib modules direct to master; this is for avoiding WSOD when switching between branches and for not getting dirty our branch work.
Don't worry about this on this feature branch :)

**Comment by dharizza** [comment]
Hey guys, ready with your comments. You can see the proposed sessions in /schedule, its path alias is /agenda. There is an extension for the module context, it allows us to set an expiring or a publishing date for contexts. Please check. Thanks.

**Comment by kporras07** [comment]
@dharizza I recently merged another branch; so we now have merge conflicts

**Comment by dharizza** [comment]
Hi, yes, we should have that limit but I didn't put it yet because we still don't have that date. Let me know if you still want me to put that expire date. :smile:

**Comment by dharizza** [comment]
Solved merge conflicts.

**Comment by kporras07** [comment]
Avoided views_ui to be activated through update_N.

**Comment by kporras07** [comment]
I added minor changes.
Looks good for me.
Merging

**Pull request merged**
