### PR TITLE
GH-5: General Permissions feature

### LINKED ISSUE #5: Permisos sobre módulo filter
Ajustar correctamente los permisos para filter

### PR DESCRIPTION
**Pull request by kporras07**
Added feature with some general (no feature related) permissions.
This should fix https://github.com/ManatiCR/dccr-2015/issues/5

### CODE REVIEW

**Comment by rigoucr** [comment]
First at all, you have merge conflicts and why you dont put this configuration in the feature dccr_ftr_config?

**Comment by kporras07** [comment]
Merge conflicts solved.
About the other part of your comment; it had been already talked :)

**Comment by rigoucr** [comment]
Why these permissions for the role drupal administrator?
- Flush caches.
- Administer entity translation.
- Administer views.

**Comment by kporras07** [comment]
Solved

**Comment by rigoucr** [comment]
Thanks :shipit:

**Pull request merged**
