### PR TITLE
54 main menu

### PR DESCRIPTION
**Pull request by kporras07**
Besides this; there is the block located up in the site.

### CODE REVIEW

**Comment by rigoucr** [comment]
please fix the merge problems

**Comment by rigoucr** [comment]
Please remove the block titles
drupal camp costa rica 2015 2015-05-19 21-35-09

**Comment by kporras07** [comment]
Only to ensure they are in db; I added a call to _block_rehash.

**Comment by kporras07** [comment]
Merging according with talked.

**Pull request merged**
