### PR TITLE
9 payment submit webform

### PR DESCRIPTION
**Pull request by kporras07**
Look https://manati.atlassian.net/browse/DCCR-9

### CODE REVIEW

**Comment by rigoucr** [comment]
The fields in the entity webform does not exist

**Comment by kporras07** [comment]
Review it again please.
Run `drush fra -y`

**Comment by rigoucr** [comment]
Thanks, now, we have some problems:
The functionality to approve one user register does not exist
The the rule to notify on approval has errors, here the detail: Error: Data selector message:field-approved-user for parameter data is invalid.

**Comment by kporras07** [comment]
@rigoucr Updated with your comments

**Comment by rigoucr** [comment]
thanks, everything looks good

**Comment by rigoucr** [comment]
:shipit:

**Pull request merged**
