### PR TITLE
Frontpage community

### PR DESCRIPTION
**Pull request by betovarg**

### CODE REVIEW

**Comment by betovarg** [comment]
@rigoucr to test: devel generate 10 users, click flag on profile, add role active member. That should make it appear in the homepage

**Comment by rigoucr** [comment]
In the design the image look like a circle, here is more like a oval @betovarg

**Comment by betovarg** [comment]
fixing it with a new image style :ear:

**Comment by rigoucr** [comment]
nice :+1:

**Comment by rigoucr** [comment]
much better :D :shipit: @betovarg

**Comment by betovarg** [comment]
booyah :boar:

**Pull request merged**
