### PR TITLE
Some landing pages

### PR DESCRIPTION
**Pull request by kporras07**
This should contains:
DCCR-12
DCCR-31
DCCR-33
DCCR-37
DCCR-35
DCCR-38

This is now ready for your review: @rigoucr @dharizza

### CODE REVIEW

**Comment by kporras07** [comment]
I was having some uuid fpp warnings.
If you get them; please open a ticket and ignore them from this PR.
I'll go back to them later

**Comment by dharizza** [comment]
Hi, we just one problem here, the views-tracks-block is not beeing shown even when the tracks terms do exist. Please check. Thanks.

**Comment by kporras07** [comment]
oops; I had forgot to add the view to the feature. 
Could you take a look now? Please @dharizza

**Comment by dharizza** [comment]
This looks great now. Thanks. :shipit:

**Pull request merged**
